version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - 8501:8501
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    working_dir: /app
    command: streamlit run app.py

volumes:
  postgres_data:
